services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=servicepulse'
      - 'POSTGRES_PASSWORD=mysecretpassword' # Şifreyi daha spesifik yapalım
      - 'POSTGRES_USER=admin'                 # Kullanıcıyı admin yapalım
    ports:
      - '5433:5432' # Bilgisayarındaki 5433'ü Docker'daki 5432'ye bağladık